/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * WaitTimeCalculationApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { NewUserDto } from "../../../models";

export const getPostApiUserRegisterResponseMock = (
  overrideResponse: Partial<Extract<NewUserDto, object>> = {},
): NewUserDto =>
  faker.helpers.arrayElement([
    {
      userName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      email: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      token: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      userName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      email: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      token: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      userName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      email: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      token: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
  ]);

export const getPostApiUserLoginResponseMock = (
  overrideResponse: Partial<Extract<NewUserDto, object>> = {},
): NewUserDto =>
  faker.helpers.arrayElement([
    {
      userName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      email: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      token: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      userName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      email: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      token: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      userName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      email: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      token: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
  ]);

export const getPostApiUserRegisterMockHandler = (
  overrideResponse?:
    | NewUserDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<NewUserDto> | NewUserDto),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/user/register",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostApiUserRegisterResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostApiUserLoginMockHandler = (
  overrideResponse?:
    | NewUserDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<NewUserDto> | NewUserDto),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/user/login",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostApiUserLoginResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getUserMock = () => [
  getPostApiUserRegisterMockHandler(),
  getPostApiUserLoginMockHandler(),
];
