/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * WaitTimeCalculationApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { LoginDto, RegisterDto } from "../../../models";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

export const postApiUserRegister = (
  registerDto: RegisterDto,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/user/register`,
    method: "POST",
    headers: { "Content-Type": "application/json-patch+json" },
    data: registerDto,
    signal,
  });
};

export const getPostApiUserRegisterMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiUserRegister>>,
    TError,
    { data: RegisterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiUserRegister>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  const mutationKey = ["postApiUserRegister"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiUserRegister>>,
    { data: RegisterDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiUserRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiUserRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiUserRegister>>
>;
export type PostApiUserRegisterMutationBody = RegisterDto;
export type PostApiUserRegisterMutationError = ErrorType<unknown>;

export const usePostApiUserRegister = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiUserRegister>>,
      TError,
      { data: RegisterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiUserRegister>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  return useMutation(
    getPostApiUserRegisterMutationOptions(options),
    queryClient,
  );
};
export const postApiUserLogin = (loginDto: LoginDto, signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/user/login`,
    method: "POST",
    headers: { "Content-Type": "application/json-patch+json" },
    data: loginDto,
    signal,
  });
};

export const getPostApiUserLoginMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiUserLogin>>,
    TError,
    { data: LoginDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiUserLogin>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationKey = ["postApiUserLogin"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiUserLogin>>,
    { data: LoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiUserLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiUserLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiUserLogin>>
>;
export type PostApiUserLoginMutationBody = LoginDto;
export type PostApiUserLoginMutationError = ErrorType<unknown>;

export const usePostApiUserLogin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiUserLogin>>,
      TError,
      { data: LoginDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiUserLogin>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  return useMutation(getPostApiUserLoginMutationOptions(options), queryClient);
};
