/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * WaitTimeCalculationApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface LinesResponseDto {
  id?: string;
  title?: string;
  /** @nullable */
  averageWaitTime?: number | null;
  isEntry?: boolean;
}
