/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * WaitTimeCalculationApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { LineResponseDto, LinesResponseDto } from "../../../models";

export const getGetApiLineResponseMock = (): LinesResponseDto[] =>
  faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      averageWaitTime: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.number.float({ fractionDigits: 2 }),
          null,
        ]),
        undefined,
      ]),
      currentLineEntryId: faker.helpers.arrayElement([
        faker.helpers.arrayElement([faker.string.uuid(), null]),
        undefined,
      ]),
    })),
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      averageWaitTime: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.number.float({ fractionDigits: 2 }),
          null,
        ]),
        undefined,
      ]),
      currentLineEntryId: faker.helpers.arrayElement([
        faker.helpers.arrayElement([faker.string.uuid(), null]),
        undefined,
      ]),
    })),
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      averageWaitTime: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.number.float({ fractionDigits: 2 }),
          null,
        ]),
        undefined,
      ]),
      currentLineEntryId: faker.helpers.arrayElement([
        faker.helpers.arrayElement([faker.string.uuid(), null]),
        undefined,
      ]),
    })),
  ]);

export const getPostApiLineResponseMock = (
  overrideResponse: Partial<Extract<LineResponseDto, object>> = {},
): LineResponseDto =>
  faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      explanation: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      explanation: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      explanation: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
  ]);

export const getGetApiLineIdResponseMock = (
  overrideResponse: Partial<Extract<LineResponseDto, object>> = {},
): LineResponseDto =>
  faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      explanation: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      explanation: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      explanation: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      ...overrideResponse,
    },
  ]);

export const getGetApiLineMockHandler = (
  overrideResponse?:
    | LinesResponseDto[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<LinesResponseDto[]> | LinesResponseDto[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/line",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiLineResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostApiLineMockHandler = (
  overrideResponse?:
    | LineResponseDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<LineResponseDto> | LineResponseDto),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/line",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostApiLineResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetApiLineIdMockHandler = (
  overrideResponse?:
    | LineResponseDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<LineResponseDto> | LineResponseDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/line/:id",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiLineIdResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getLineMock = () => [
  getGetApiLineMockHandler(),
  getPostApiLineMockHandler(),
  getGetApiLineIdMockHandler(),
];
