/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * WaitTimeCalculationApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  LineRequestDto,
  LineResponseDto,
  LinesResponseDto,
  ProblemDetails,
} from "../../../models";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

export const getApiLine = (signal?: AbortSignal) => {
  return customInstance<LinesResponseDto[]>({
    url: `/api/line`,
    method: "GET",
    signal,
  });
};

export const getGetApiLineQueryKey = () => {
  return [`/api/line`] as const;
};

export const getGetApiLineQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiLine>>,
  TError = ErrorType<ProblemDetails>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiLine>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiLineQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLine>>> = ({
    signal,
  }) => getApiLine(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiLine>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiLineQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiLine>>
>;
export type GetApiLineQueryError = ErrorType<ProblemDetails>;

export function useGetApiLine<
  TData = Awaited<ReturnType<typeof getApiLine>>,
  TError = ErrorType<ProblemDetails>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiLine>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLine>>,
          TError,
          Awaited<ReturnType<typeof getApiLine>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLine<
  TData = Awaited<ReturnType<typeof getApiLine>>,
  TError = ErrorType<ProblemDetails>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiLine>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLine>>,
          TError,
          Awaited<ReturnType<typeof getApiLine>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLine<
  TData = Awaited<ReturnType<typeof getApiLine>>,
  TError = ErrorType<ProblemDetails>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiLine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiLine<
  TData = Awaited<ReturnType<typeof getApiLine>>,
  TError = ErrorType<ProblemDetails>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiLine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiLineQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiLine = (
  lineRequestDto: LineRequestDto,
  signal?: AbortSignal,
) => {
  return customInstance<LineResponseDto>({
    url: `/api/line`,
    method: "POST",
    headers: { "Content-Type": "application/json-patch+json" },
    data: lineRequestDto,
    signal,
  });
};

export const getPostApiLineMutationOptions = <
  TError = ErrorType<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiLine>>,
    TError,
    { data: LineRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiLine>>,
  TError,
  { data: LineRequestDto },
  TContext
> => {
  const mutationKey = ["postApiLine"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiLine>>,
    { data: LineRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiLine(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiLineMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiLine>>
>;
export type PostApiLineMutationBody = LineRequestDto;
export type PostApiLineMutationError = ErrorType<ProblemDetails>;

export const usePostApiLine = <
  TError = ErrorType<ProblemDetails>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiLine>>,
      TError,
      { data: LineRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiLine>>,
  TError,
  { data: LineRequestDto },
  TContext
> => {
  return useMutation(getPostApiLineMutationOptions(options), queryClient);
};
export const getApiLineId = (id: string, signal?: AbortSignal) => {
  return customInstance<LineResponseDto>({
    url: `/api/line/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiLineIdQueryKey = (id: string) => {
  return [`/api/line/${id}`] as const;
};

export const getGetApiLineIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiLineId>>,
  TError = ErrorType<ProblemDetails>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiLineId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiLineIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLineId>>> = ({
    signal,
  }) => getApiLineId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiLineId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiLineIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiLineId>>
>;
export type GetApiLineIdQueryError = ErrorType<ProblemDetails>;

export function useGetApiLineId<
  TData = Awaited<ReturnType<typeof getApiLineId>>,
  TError = ErrorType<ProblemDetails>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiLineId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLineId>>,
          TError,
          Awaited<ReturnType<typeof getApiLineId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLineId<
  TData = Awaited<ReturnType<typeof getApiLineId>>,
  TError = ErrorType<ProblemDetails>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiLineId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLineId>>,
          TError,
          Awaited<ReturnType<typeof getApiLineId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLineId<
  TData = Awaited<ReturnType<typeof getApiLineId>>,
  TError = ErrorType<ProblemDetails>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiLineId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiLineId<
  TData = Awaited<ReturnType<typeof getApiLineId>>,
  TError = ErrorType<ProblemDetails>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiLineId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiLineIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
