/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * WaitTimeCalculationApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

export const postApiLineEntry = (
  postApiLineEntryBody: string,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/lineEntry`,
    method: "POST",
    headers: { "Content-Type": "application/json-patch+json" },
    data: postApiLineEntryBody,
    signal,
  });
};

export const getPostApiLineEntryMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiLineEntry>>,
    TError,
    { data: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiLineEntry>>,
  TError,
  { data: string },
  TContext
> => {
  const mutationKey = ["postApiLineEntry"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiLineEntry>>,
    { data: string }
  > = (props) => {
    const { data } = props ?? {};

    return postApiLineEntry(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiLineEntryMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiLineEntry>>
>;
export type PostApiLineEntryMutationBody = string;
export type PostApiLineEntryMutationError = ErrorType<unknown>;

export const usePostApiLineEntry = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiLineEntry>>,
      TError,
      { data: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiLineEntry>>,
  TError,
  { data: string },
  TContext
> => {
  return useMutation(getPostApiLineEntryMutationOptions(options), queryClient);
};
export const putApiLineEntryId = (id: string, signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/lineEntry/${id}`,
    method: "PUT",
    signal,
  });
};

export const getPutApiLineEntryIdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiLineEntryId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiLineEntryId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["putApiLineEntryId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiLineEntryId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return putApiLineEntryId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiLineEntryIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiLineEntryId>>
>;

export type PutApiLineEntryIdMutationError = ErrorType<unknown>;

export const usePutApiLineEntryId = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiLineEntryId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiLineEntryId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getPutApiLineEntryIdMutationOptions(options), queryClient);
};
