/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * WaitTimeCalculationApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { EnterResponseDto, ExitResponseDto } from "../../../models";

export const getPostApiLineEntryResponseMock = (
  overrideResponse: Partial<Extract<EnterResponseDto, object>> = {},
): EnterResponseDto =>
  faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      enteredAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      enteredAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      enteredAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      ...overrideResponse,
    },
  ]);

export const getPutApiLineEntryIdResponseMock = (
  overrideResponse: Partial<Extract<ExitResponseDto, object>> = {},
): ExitResponseDto =>
  faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      enteredAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      exitedAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      enteredAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      exitedAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      enteredAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      exitedAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      ...overrideResponse,
    },
  ]);

export const getPostApiLineEntryMockHandler = (
  overrideResponse?:
    | EnterResponseDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<EnterResponseDto> | EnterResponseDto),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/lineEntry",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostApiLineEntryResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPutApiLineEntryIdMockHandler = (
  overrideResponse?:
    | ExitResponseDto
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ExitResponseDto> | ExitResponseDto),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/lineEntry/:id",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPutApiLineEntryIdResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getLineEntryMock = () => [
  getPostApiLineEntryMockHandler(),
  getPutApiLineEntryIdMockHandler(),
];
